<?php

namespace Tests\Feature\Feature;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class CardCheckoutTest extends TestCase
{
    use DatabaseTransactions;

    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        /*\Mail::pretend();*/
    }


}
